config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users
  resources :departments
  resources :user, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    member do
      get :change_password
      get :edit_info
      patch :update_info
    end
  end

  resources :departments do
    resources :users_department, only: [:edit, :update]
  end

  resources :departments do
    resources :projects_department, only: [:edit, :update]
  end

  resources :projects do
    resources :user_projects
  end

  scope "(:locale)", locale: /en|vi/ do
  end
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :users
  has_many :projects, dependent: :destroy

  belongs_to :leader, class_name: 'User', foreign_key: 'user_id', optional: true

  def is_leader?(user)
    # leader là đối tượng liên kết giữa Department và User, ở đây so sánh đối tượng leader với user
    leader == user
  end

  def member_department?(user)
    user.department_id == id
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController

  def index
    @departments = Department.paginate(page: params[:page], per_page: 10)
    authorize @departments
  end

  def show
    @department = Department.find(params[:id])
    @users = User.where(department_id: params[:id])
    @user_leader = User.find_by(id: @department.user_id)
    @project = Project.where(department_id: params[:id])
    authorize @department
  end

  def new
    @department = Department.new
    authorize @department
  end

  def create
    @department = Department.new(departments_param)
    authorize @department
    if @department.save
      flash[:success] = "Create to Success!"
      redirect_to departments_path
    else
      flash[:danger] = "Error Create"
      redirect_to action: :new
    end
  end

  def edit
    @department = Department.find(params[:id])
    authorize @department
  end

  def update
    @department = Department.find(params[:id])
    authorize @department
    if @department.update(departments_param)
      redirect_to action: :index
      flash[:success] = "Update to Success!"
    else
      render action: :edit
      flash[:danger] = "Error!"
    end
  end

  def destroy
    @department = Department.find(params[:id])
    authorize @department
    if @department.destroy!
      flash[:success] = 'Department was successfully deleted.'
    else
      flash[:error] = 'Unable to delete Parts due to foreign key binding'
    end
    redirect_to departments_path
  end

  def remove_user_from_department
    department = Department.find(department_id)
    user = department.user.find(user_id)
    user.destroy

    render action: :index
  end

  private

  def departments_param
    params.require(:department).permit(:name, :description, :user_id)
  end

end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/edit.html.erb
<div style="width: 400px; margin-top: 20px">
  <h2>Edit Department</h2>
  <%= form_with(model: @department, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :Department_name %>
      <%= f.text_field :name, class: 'form-control col-md-7' %>
    </div>

    <div class="field form-group">
      <%= f.label :leader %><br/>
      <%= f.collection_select :user_id, User.where(department_id: @department.id), :id, :name, include_blank: true %>
    </div>
    <%= f.submit "Update", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/departments/index.html.erb
<% provide(:title, 'All Department') %>

<h2 class="text-center py-3">All Department</h2>

<% if current_user.admin? %>
  <%= link_to "+ Add New Department", new_department_path, class: "btn btn-secondary" %>
<% end %>

<%= will_paginate %>

<table class="table mt-3">
  <thead>
  <tr class="thead-dark text-center">
    <th scope="col">STT</th>
    <th scope="col">Name</th>
    <th scope="col">Number Member</th>
    <th scope="col">Number Project</th>
    <th scope="col">Leader</th>
    <th scope="col">Description</th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @departments.each_with_index do |department, index| %>
    <tr class="text-center">
      <td> <%= index + 1 %></td>
      <td class="detail">
        <% if current_user.admin? || department.is_leader?(current_user) || department.member_department?(current_user) %>
          <%= link_to department.name, department_path(department) %>
        <% else %>
          <%= department.name %>
        <% end %>
      </td>
      <td> <%= department.users.length %></td>
      <td> <%= department.projects.length %></td>
      <td>
        <%= department.users.find_by(id: department.user_id)&.name || "No Leader" %>
      </td>
      <td> <%= department.description %></td>
      <td>
        <% if current_user.admin? %>
          <%= link_to "Edit", edit_department_path(department), class: "btn btn-primary btn_action" %>
        <% end %>
      </td>
      <td>
        <% if current_user.admin? %>
          <%= button_to 'Destroy', department, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn_action" %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/departments/new.html.erb
<% provide(:title, 'Add Department') %>
<div style="width: 400px">
  <h2 class="text-center">Add New Department</h2>

  <%= form_with(model: @department, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <%= f.submit 'Add department', class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/departments/show.html.erb
<h2 class="text-center">Information Department</h2>
<h4>
  ** <%= @department.name %> **
</h4>
<strong>Leader: </strong> <%= @user_leader&.name %><br/>
<strong>Number member: </strong> <%= @department.users.length %><br/>
<strong>Number project: </strong> <%= @department.projects.length %><br/>
<strong>Description: </strong> <%= @department.description %><br/>

<br>
<h4 class="text-center">List User to Department</h4>

<% if current_user.admin? %>
  <%= link_to "+ Edit Number User to Department", edit_department_users_department_path(@department), class: "btn btn-secondary" %>
<% end %>

<table class="table mt-3">
  <thead>
  <tr class="thead-dark text-center">
    <th scope="col">ID</th>
    <th scope="col">Name</th>
    <th scope="col">Email</th>
    <th scope="col">Role</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <% @users.each_with_index do |user, index| %>
    <tr class="text-center">
      <td> <%= index + 1 %></td>
      <td>
        <% if current_user.admin? || current_user.hr? || current_user == user || current_user.id == user.department&.user_id %>
          <%= link_to user.name, user_path(user) %>
        <% else %>
          <%= user.name %>
        <% end %>
      </td>
      <td> <%= user.email %></td>
      <% if @user_leader&.id == user.id %>
        <td>Leader</td>
      <% else %>
        <td>employee</td>
      <% end %>
    </tr>
  <% end %>
  <tbody>
  </tbody>
</table>

<br>

<h4 class="text-center">List Project to Department</h4>

<% if current_user.admin? %>
  <%= link_to "+ Edit Number Project to Department", edit_department_projects_department_path(@department), class: "btn btn-secondary" %>
<% end %>

<table class="table mt-3" style="margin-bottom: 150px">
  <thead>
  <tr class="thead-dark text-center">
    <th scope="col">ID</th>
    <th scope="col">Name</th>
    <th scope="col">Number Member</th>
    <th scope="col">Leader Project</th>
    <th scope="col"></th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <% @project.each_with_index do |project, index| %>
    <tr class="text-center">
      <td> <%= index + 1 %></td>
      <td>
        <% if current_user.admin? || project.member_project?(current_user) || project.department&.is_leader?(current_user) %>
          <%= link_to project.name, project_path(project) %>
        <% else %>
          <%= project.name %>
        <% end %>
      </td>
      <td> <%= project.user_projects.length %></td>
      <td>
        <% project.user_projects.select { |user_project| p user_project.is_leader == "PM" }.each do |user_project| %>
          <%= user_project.user.name %>
        <% end %>
      </td>
    </tr>
  <% end %>
  <tbody>
  </tbody>
</table>