config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users
  resources :departments
  resources :user, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    member do
      get :change_password
      get :edit_info
      patch :update_info
    end
  end

  resources :departments do
    resources :users_department, only: [:edit, :update]
  end

  resources :departments do
    resources :projects_department, only: [:edit, :update]
  end

  resources :projects do
    resources :user_projects
  end

  scope "(:locale)", locale: /en|vi/ do
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :department, optional: true
  has_many :user_projects,  dependent: :destroy
  has_many :users, through: :user_projects # dependent: :destroy
  enum status: { Processing: false, Done: true }

  def member_project?(user)
    # users là đối tượng liên kết giữa model project và user
    users.include?(user)
  end

  # check current_user có phải là PM của project không
  def pm?(user)
    user_projects.where(is_leader: true).exists?(user_id: user)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  rescue_from ActiveRecord::InvalidForeignKey do |exception|
    redirect_to projects_path, alert: "Error! Unable to delete Parts due to foreign key binding!"
  end
  def index
    @projects = Project.all
    authorize @projects
  end

  def show
    @project = Project.find(params[:id])
    @users_project = UserProject.where(project_id: params[:id])
    authorize @project
    # lấy ra mảng user là leader và thuộc project
    @users_leader = UserProject.where(project_id: @project.id, is_leader: true)
  end

  def new
    @departments = Department.all
    @project = Project.new
    authorize @project
  end

  def create
    @project = Project.new(project_param)
    authorize @project
    if @project.save
      flash[:success] = "Create to Success!"
      redirect_to projects_path
    else
      flash[:danger] = "Error"
      redirect_to action: :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    authorize @project
  end

  def update
    # byebug
    @project = Project.find(params[:id])
    authorize @project
    if @project.update(project_param)
      redirect_to action: :index
      flash[:success] = "Update to Success!"
    else
      render action: :edit
      flash[:danger] = "Error!"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    authorize @project
    if @project.destroy
      flash[:success] = 'Project was successfully deleted.'
    else
      flash[:error] = 'Unable to delete Parts due to foreign key binding'
    end
    redirect_to projects_path
  end


  private

  def project_param
    params.require(:project).permit(:name, :department_id, :status).tap do |whitelisted|
      whitelisted[:status] = params[:project][:status].to_s == "true" ? true : false
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<div style="width: 400px; margin-top: 20px">
  <h2>Edit Project</h2>
  <%= form_with(model: @project, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :Project_name %>
      <%= f.text_field :name, class: 'form-control col-md-7' %>
    </div>

    <div class="field form-group d-flex">
      <%= f.label :department_id, class:"mr-2" %><br/>
      <%= f.collection_select :department_id, Department.all, :id, :name, include_blank: true %>
    </div>

    <div class="field form-group d-flex">
      <%= f.label :status, class:"mr-5" %><br/>
      <% p @project.status %><br/>

      <div>
        <%= f.radio_button :status, true, checked: @project.status != "Processing" %>
        <%= f.label :status, "Done" %>
        <br>
        <%= f.radio_button :status, false, checked: @project.status == "Processing" %>
        <%= f.label :status, "Processing" %>
      </div>
    </div>

    <%= f.submit "Update", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/projects/index.html.erb
<% provide(:title, 'All Project') %>

<h2 class="text-center py-3">All Project</h2>

<% if current_user.admin? %>
  <%= link_to "+ Add New Project", new_project_path, class: "btn btn-secondary" %>
<% end %>
<%#= will_paginate %>

<table class="table mt-3">
  <thead>
  <tr class="thead-dark text-center">
    <th scope="col">STT</th>
    <th scope="col">Name</th>
    <th scope="col">Leader Project</th>
    <th scope="col">Number Member</th>
    <th scope="col">Department</th>
    <th scope="col">Status</th>
    <th scope="col">Project Time</th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @projects.each_with_index do |project, index| %>
    <% if current_user.admin? || project.member_project?(current_user) || project.department&.is_leader?(current_user)%>
      <tr class="text-center">
        <td> <%= index + 1 %></td>
        <td class="detail">
          <% if current_user.admin? || project.member_project?(current_user) || project.department&.is_leader?(current_user) %>
            <%= link_to project.name, project_path(project) %>
          <% else %>
            <%= project.name %>
          <% end %>
        </td>
        <td>
          <% project.user_projects.each do |user_project| %>
            <% if user_project.PM? %>
              <%= user_project.user.name %><br>
            <% end %>
          <% end %>
        </td>
        <td> <%= project.user_projects.length %></td>
        <td> <%= Department.find_by(id: project.department_id)&.name %></td>
        <td> <%= project.status %></td>
        <td>
          <%= project.user_projects.first&.start_date %>
          -
          <%= project.user_projects.first&.end_date %>
        </td>
<!--        <td>-->
          <%# if current_user.admin? || project.member_project?(current_user) || project.department&.is_leader?(current_user) %>
            <%#= link_to "Detail", project_path(project), class: "btn btn-info btn_action" %>
          <%# end %>
<!--        </td>-->
        <td>
          <% if current_user.admin? %>
            <%= link_to "Edit", edit_project_path(project), class: "btn btn-primary btn_action" %>
          <% end %>
        </td>
        <td>
          <% if current_user.admin? %>
            <%= button_to 'Destroy', project, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn_action" %>
          <% end %>
        <td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<% provide(:title, 'Add Project') %>
<div style="width: 400px">
  <h2 class="text-center">Add New Project</h2>

  <%= form_with(model: @project, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <%= f.submit 'Add Project', class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/projects/show.html.erb
<h2 class="text-center">Information Project</h2>
<h4>
  ** <%= @project.name %> **
</h4>
<strong>Number member: </strong> <%= @project.user_projects.length %><br/>

<div class="d-flex">
  <strong>PM: </strong>
  <div class="ml-2">
    <% @users_leader.each do |user_leader| %>
      <%= user_leader.user.name %><br>
    <% end %>
  </div>
</div>

<br>

<h3 class="text-center">List User to Project</h3>

<% if current_user.admin? || @project.department.is_leader?(current_user) || @project.pm?(current_user) %>
  <%= link_to "+ Add New User to Project", new_project_user_project_path(@project), class: "btn-add btn btn-secondary" %>
<% end %>

<table class="table mt-3">
  <thead>
  <tr class="thead-dark text-center">
    <th scope="col">STT</th>
    <th scope="col">User Name</th>
    <th scope="col">Role</th>
    <th scope="col">Department</th>
    <th scope="col" style="width:100px"></th>
    <th scope="col" style="width:100px"></th>
    <th scope="col" style="width:100px"></th>
  </tr>
  </thead>
  <% @users_project.each_with_index do |user_project, index| %>
    <tr class="text-center">
      <td> <%= index + 1 %></td>
      <td>
        <% if current_user.admin? || current_user.hr? || @project.pm?(current_user) || current_user == user_project.user || current_user.id == user_project.user.department&.user_id %>
          <%= link_to user_project.user.name, user_path(user_project.user.id) %>
        <% else %>
          <%= user_project.user.name %>
        <% end %>
      </td>
      <td>
        <%= user_project.is_leader %>
      </td>
      <td> <%= user_project.user.department&.name %></td>
      <td>
        <% if current_user.admin? || @project.department.is_leader?(current_user) %>
          <%= link_to "Edit", edit_project_user_project_path(@project, user_project, user_project.user), class: "btn btn-primary btn_action" %>
        <% end %>
      </td>
      <td>
        <% if current_user.admin? || @project.department.is_leader?(current_user) || @project.pm?(current_user) %>
          <%= button_to "Destroy", project_user_project_path(@project, user_project), method: :delete, class: "btn btn-danger btn_action" %>
        <% end %>
      </td>
    </tr>
  <% end %>
  <tbody>
  </tbody>
</table>