config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users
  resources :departments
  resources :user, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    member do
      get :change_password
      get :edit_info
      patch :update_info
    end
  end

  resources :departments do
    resources :users_department, only: [:edit, :update]
  end

  resources :departments do
    resources :projects_department, only: [:edit, :update]
  end

  resources :projects do
    resources :user_projects
  end

  scope "(:locale)", locale: /en|vi/ do
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  friendly_id :slug_candidates, use: :slugged

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :department, optional: true #, dependent: :destroy
  has_many :user_projects , dependent: :destroy
  has_many :projects, through: :user_projects
  enum role: { admin: 1, hr: 2, employee: 3 }

  before_destroy :check_user_projects

  validates :name, presence: true, length: { maximum: 30 }

  validates :email, presence: true,
            length: { maximum: 50 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: true

  private

  def slug_candidates
    "#info"
  end

  def check_user_projects
    if user_projects.exists?
      errors.add(:base, "This user has related user projects. Please delete them first.")
      throw :abort
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  rescue_from ActiveRecord::InvalidForeignKey do |exception|
    flash[:alert] = "Error! Unable to delete Parts due to foreign key binding!"
    redirect_to user_index_path
  end

  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = User.friendly.find(params[:id])
    authorize @user
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user
    p @user
    if @user.save
      flash[:success] = t('activerecord.success.create')
      redirect_to user_index_path
    else
      flash[:alert] = @user.errors.full_messages.join('. ')
      redirect_to user_index_path
    end
  end

  def destroy
    @user = User.friendly.find(params[:id])
    authorize @user
    if @user.destroy
      flash[:success] = t('activerecord.success.destroy')
      redirect_to user_index_path
    else
      flash[:error] = @user.errors.full_messages.join(". ")
      redirect_to user_index_path
    end
  end

  def edit_info
    @user = User.friendly.find(params[:id])
    # authorize @user
  end

  def update_info
    @user = User.friendly.find(params[:id])
    # authorize @user
    if @user.update(edit_info_params)
      redirect_to user_path(@user)
      flash[:success] = "User info was successfully updated."
    else
      render :edit
    end
  end

  def edit
    @user = User.friendly.find(params[:id])
    # authorize @user
  rescue
    flash[:danger] = "Can't edit"
    redirect_to user_index_path
  end

  def update
    role_value = 1 if user_params[:role] == "admin"
    role_value = 2 if user_params[:role] == "hr"
    role_value = 3 if user_params[:role] == "employee"

    @user = User.friendly.find(params[:id])
    # authorize @user

    if @user.update(role: role_value, name: user_params[:name])
      redirect_to user_index_path
      flash[:success] = t('activerecord.success.update')
    else
      redirect_to user_index_path
      flash[:danger] = t('activerecord.errors.messages.update')
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :address, :birthday, :department, :role)
  end

  def edit_info_params
    params.require(:user).permit(:name, :address, :birthday)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/edit.html.erb
<div style="width: 400px; margin-top: 20px">
  <h2>Edit User <%= @user.name %></h2>
  <%= form_with(model: @user, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :user %>
      <%= f.text_field :name, class: 'form-control col-md-7' %>
    </div>
    <div class="field form-group">
      <%= f.label :role %><br/>
      <%= f.select :role, options_for_select(User.roles.keys.map { |r| [r, r] }, @user.role) %>
    </div>

    <%= f.submit "Update", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/user/edit_info.html.erb
<div style="width: 400px">
  <h1 class="text-center">Edit User Info</h1>

  <%= form_for @user, url: update_info_user_path, method: :patch do |f| %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control', required: true, :disabled => true %>
    </div>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>

    <div class="field form-group">
      <%= f.label :birthday %><br/>
      <%= f.text_field :birthday, class: "form-control" %>
    </div>

    <%= f.submit 'Update Info', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/user/index.html.erb
<% provide(:title, 'ALl User') %>

<h2 class="text-center py-3">User</h2>

<% if current_user.admin? %>
  <%= link_to "+ Add New User", new_user_path, class: "btn btn-secondary" %>
<% end %>


<table class="table mt-3">
  <thead>
  <tr class="thead-dark text-center">
    <th scope="col">ID</th>
    <th scope="col"> <%= t('activerecord.attributes.user.name') %></th>
    <th scope="col"> <%= t('activerecord.attributes.user.email') %></th>
    <th scope="col"> <%= t('activerecord.attributes.user.address') %></th>
    <th scope="col"> <%= t('activerecord.attributes.user.birthday') %></th>
    <th scope="col"> <%= t('activerecord.attributes.user.role') %></th>
    <th scope="col"></th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each_with_index do |user, index| %>
    <tr class="text-center">
      <td> <%= index + 1 %></td>
      <td class="detail">
        <% if current_user.admin? || current_user.hr? || current_user == user || current_user.id == user.department&.user_id %>
          <%= link_to user.name, user_path(user) %>
        <% else %>
          <%= user.name %>
        <% end %>
      </td>
      <td> <%= user.email %></td>
      <td> <%= user.address %></td>
      <td> <%= user.birthday %></td>
      <td>
        <% if user.role == "admin" %>
          <%= t('activerecord.models.admin') %>
        <% elsif user.role == "hr" %>
          <%= t('activerecord.models.hr') %>
        <% elsif user.role == "employee" %>
          <%= t('activerecord.models.employee') %>
        <% end %>
      </td>
      <td>
        <%# if current_user.admin? %>
        <%= link_to "Edit", edit_user_path(user), class: "btn btn-primary btn_action" %>
        <%# end %>
      </td>
      <td>
        <% if current_user.admin? %>
          <%= button_to 'Destroy', user, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn_action" %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/user/new.html.erb
<div style="width: 400px; margin-bottom: 100px">
  <h2 class="text-center my-3">Add User</h2>
  <%= form_with(model: @user, url: user_index_path, local: true) do |f| %>
    <div class="field form-group">
      <%= f.label :email %><br/>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :password %>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br/>
      <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :password_confirmation %><br/>
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :name %><br/>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :address %><br/>
      <%= f.text_field :address, class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :role %><br/>
      <%= f.select :role, options_for_select(User.roles.keys.map { |r| [r, r] }, @user.role), class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :birthday %><br/>
      <%= f.date_field :birthday, class: "form-control" %>
    </div>
    <br>
    <%= f.submit "Create User" %>
  <% end %>
</div>

app/views/user/show.html.erb
<h2>Thông tin cá nhân</h2>
<div class="card" style="width: 22rem">
<!--  <img class="card-img-top" src="..." alt="Card image cap">-->
  <div class="card-body">
    <h5 class="card-title">
      <%= @user.name %>
    </h5>
    <strong>Email: </strong> <%= @user.email %><br/>
    <strong>Address: </strong> <%= @user.address %><br/>
    <strong>Birthday: </strong> <%= @user.birthday %><br/>
    <strong>Role: </strong> <%= @user.role %><br/>
    <strong>Department: </strong> <%= @user.department&.name %><br/>

  </div>
</div>