config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users
  resources :departments
  resources :user, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    member do
      get :change_password
      get :edit_info
      patch :update_info
    end
  end

  resources :departments do
    resources :users_department, only: [:edit, :update]
  end

  resources :departments do
    resources :projects_department, only: [:edit, :update]
  end

  resources :projects do
    resources :user_projects
  end

  scope "(:locale)", locale: /en|vi/ do
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails
    Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Đỗ Mạnh</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<ul class="nav py-3 bg-dark mb-3" style="justify-content: space-between">
  <div class="d-flex">
    <li class="nav-item">
      <%= link_to 'Home', root_path, class: "nav-link text-white" %>
    </li>

    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Department', departments_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Project', projects_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to 'List User', user_index_path, class: "nav-link text-white" %>
      </li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle nav-link text-white" data-toggle="dropdown"> Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu pl-3 px-3" style="width: 200px">
          <li><%= link_to "Update Info", edit_info_user_path(current_user), class: "btn btn-secondary btn_dropdown" %></li>
          <li><%= link_to "Change Password", edit_user_registration_path(current_user), class: "btn btn-secondary btn_dropdown" %></li>
          <li>
            <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link btn btn-secondary btn_dropdown" %>
          </li>
        </ul>
      </div>
      <div class="d-flex" style="margin-right: 60px">
        <div class="locale-select">
          <button class='btn btn-secondary <%= I18n.locale == :vi ? 'active' : '' %>'>
            <%= link_to "VI", locale: "vi" %>
          </button>
          <button class='btn btn-secondary <%= I18n.locale == :en ? 'active' : '' %>'>
            <%= link_to "EN", locale: "en", class: "btn" %>
          </button>
        </div>
        <div>
          <strong style="font-size: 18px; color: white"><%= current_user.name %></strong>
          <br>
          <span style="font-size: 15px; color: white"> <%= current_user.role %></span>
        </div>

      </div>
    <% end %>

    <% unless user_signed_in? %>
      <!--    <li class="nav-item">-->
      <%#= link_to 'Sign Up', new_user_registration_path, class: "nav-link text-white" %>
      <!--    </li>-->

      <li class="nav-item">
        <%= link_to 'LogIn', new_user_session_path, class: "nav-link text-white" %>
      </li>
    <% end %>
    </ul>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">


<!--  <title><%#= full_title(yield(:title)) %></title>-->
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>
<body>
<%= render 'layouts/header' %>

<div style="padding: 0 15%">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
  <% end %>

  <%= yield %>

  <div class="container-fluid">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

</div>

<!--<div class="footer px-5">-->
  <%#= render 'layouts/footer' %>
<!--</div>-->
<br>
<%#= debug(params) if Rails.env.development? %>

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
-->
</body>
</html>